name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.23', '1.24']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: run tests
        run: go test -v ./...
      - name: check go mod tidy
        run: |
          go mod tidy
          git diff --exit-code
